### ISSUE TITLE
Simple Towns Economy

### ISSUE THREAD

**Issue by AustaniaServers** [MarkehMe/SimpleTowns-Economy#3]
Hey, I'm getting this issue every time Simple-Towns-Economy tries to complete a task - this may be when it tries to make a town and takes funds from users.
```
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at markehme.SimpleTownsEconomy.extras.Metrics.postPlugin(Metrics.java:323) ~[?:?]
at markehme.SimpleTownsEconomy.extras.Metrics.access$0(Metrics.java:316) ~[?:?]
at markehme.SimpleTownsEconomy.extras.Metrics$1.run(Metrics.java:213) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
```

**Comment by markhughes** [comment]
Oh wow, I haven't touched this plugin in forever!

@JamesHealey94 isn't maintaining [SimpleTowns](https://github.com/JamesHealey94/SimpleTowns) at the moment, and I would only advise using SimpleTowns on offline servers as it isn't UUID-based!

I can fix this up for you though.

**Comment by markhughes** [comment]
Fixed

https://dev.bukkit.org/bukkit-plugins/simpletownseconomy/files/4-simple-towns-economy-v1-1-1/

**Comment by AustaniaServers** [comment]
Thank you very much kind sir.
