### ISSUE TITLE
Still gives error after recent update.

### ISSUE THREAD

**Issue by AustaniaServers** [MarkehMe/SimpleTowns-Economy#4]
Hello, the plugin still gives this, even after the recent update:

```
[16:53:52] [Server thread/INFO]: Lego9182 issued server command: /town create Brix
[16:53:52] [Server thread/ERROR]: Could not pass event TownCreateEvent to SimpleTownsEconomy v1.1.1
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at com.gmail.jameshealey1994.simpletowns.commands.command.CreateCommand.execute(CreateCommand.java:103) [SimpleTowns.jar:?]
at com.gmail.jameshealey1994.simpletowns.commands.STCommandExecutor.onCommand(STCommandExecutor.java:48) [SimpleTowns.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
at markehme.SimpleTownsEconomy.SimpleTownsEconomy.shouldCharge(SimpleTownsEconomy.java:176) ~[?:?]
at markehme.SimpleTownsEconomy.listeners.SimpleTownsListener.onTownCreate(SimpleTownsListener.java:57) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
... 21 more
```

**Comment by markhughes** [comment]
This is a different error to the original, I'll investigate it soon

**Comment by markhughes** [comment]
Can you please try deleting your configuration files and trying again?

**Comment by AustaniaServers** [comment]
Still coming back with the same error sadly.

**Comment by AustaniaServers** [comment]
Still coming back with this:
[09:40:05] [Server thread/INFO]: BlackFighterZz issued server command: /town create bob
[09:40:05] [Server thread/ERROR]: Could not pass event TownCreateEvent to SimpleTownsEconomy v1.1.1
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at com.gmail.jameshealey1994.simpletowns.commands.command.CreateCommand.execute(CreateCommand.java:103) [SimpleTowns.jar:?]
at com.gmail.jameshealey1994.simpletowns.commands.STCommandExecutor.onCommand(STCommandExecutor.java:48) [SimpleTowns.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
at markehme.SimpleTownsEconomy.SimpleTownsEconomy.shouldCharge(SimpleTownsEconomy.java:176) ~[?:?]
at markehme.SimpleTownsEconomy.listeners.SimpleTownsListener.onTownCreate(SimpleTownsListener.java:57) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
... 21 more
[09:40:05] [Server thread/INFO]: New Town 'bob' created!
